In [2]:
#파이토치 프레임워크 불러오는 부분
import torch
import torchvision # image processing에 특화된 라이브러리
import torch.nn as nn
import torchvision.transforms as transforms # Data Augmentation에 특화된 라이브러리
import numpy as np

In [7]:
X = torch.Tensor(2,3) # 2행 3열의 텐서를 하나 생성
X.shape
X.size()

X = torch.Tensor([[1,2,3],[4,5,6]])
X

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [12]:
'''
tensor()인자값으로
data : 값지정 , 초기화
dtype
requires_grad : tensor에 대해서 미분 적용할지 여부
'''
x = torch.tensor(data=[2.0, 3.0], requires_grad=True)
x

y = x**2  # 4, 9
y

pred = 2*y +3 # 11, 21

target = torch.tensor([3.0, 4.0])  # 3, 4
target

tensor([3., 4.])

In [ ]:
'''
위에 나온 결과를 바탕으로
경사하강법을 이용해서 
미분을 사용해서 Loss에 대한 책임을 묻겠다
기울이가 계산이 될 것이다.(미분 계산)
--> BackPropagation 을 적용하려면 backward() 함수를 호출

Loss를 줄여나가 보겠다.
'''

In [13]:
loss = torch.sum(torch.abs(pred - target))
print('Loss', loss)

Loss tensor(25., grad_fn=<SumBackward0>)


In [14]:
loss.backward()

In [16]:
print(x.grad,pred.grad)

tensor([ 8., 12.]) None


<ipython-input-16-f0cd9ca8c1fa>:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  print(x.grad,pred.grad)


### Create Tensor ....Using NeuralNet

In [20]:
x = torch.randn(10,3)
y = torch.randn(10,2)
print(x)
print(y)

tensor([[ 0.6343, -0.3771, -0.1529],
        [ 0.0043,  0.3213,  0.2549],
        [-0.6464,  1.7498, -0.3769],
        [-0.1006, -1.4268,  0.8419],
        [ 1.0721,  1.5363, -2.5409],
        [-0.7414, -2.0082,  0.7942],
        [-1.2485, -1.0378,  0.1819],
        [ 0.5640,  2.0952,  0.2436],
        [-0.4538,  0.9258,  0.3400],
        [ 0.8474,  0.3718,  0.0628]])
tensor([[ 1.6591,  0.4949],
        [-0.5507,  0.3667],
        [ 1.3947,  0.2634],
        [ 1.1020,  0.6948],
        [ 1.5271, -0.0417],
        [-0.2883,  1.2307],
        [ 0.1074,  1.9449],
        [ 0.7615,  0.2145],
        [-1.5247, -0.0108],
        [ 1.0265, -0.1139]])


In [21]:
linear = nn.Linear(3,2)
print('w',linear.weight)
print('b',linear.bias)

w Parameter containing:
tensor([[ 0.5442, -0.4392, -0.3906],
        [-0.3340,  0.1578,  0.1843]], requires_grad=True)
b Parameter containing:
tensor([-0.2954, -0.2118], requires_grad=True)


In [23]:
# 객체출력, parameters()함수는 모델안의 학습의 주체인 w, b를 내포하고 있는 객체
# parameters() 함수는 w,b를 해킹한 함수이다.
print(linear.parameters())

# loss function을 미리 선정의 해두었다.
loss_function = nn.MSELoss()

# optimizer(하산하는 방법)를 미리 정의
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

# 위에서 만든 모델에 값을 입력...결과로 예측값이 나온다
pred=linear(x)

# 정답과 예측값을 이용해서 위에서 선정의한 Loss 를 계산...L(W)
loss = loss_function(pred, y)
print('loss before step BackPropagation',loss.item())

<generator object Module.parameters at 0x000002422DBEBDD0>
loss before step BackPropagation 1.2180315256118774


In [24]:
'''
loss값이 나왔다는 것은
모델의 예측값에 대한 잘잘못을 정량화 했다는 것이다.

이 값을 바탕으로 BackPropagation을 하면 w, b에 대한 미분값
즉 얼마만큼 보정해야 하는지의 값이 나온다.
그 값을 이용해서 다시 하강(기울기 수정)하기 떄문에
2번쨰에는 Loss가 줄어들어야 한다.
'''
loss.backward() #loss값에 대한 w의 책임을 묻는다...미분을 적용. grad
print('dL/dw', linear.weight.grad)
print('dL/db', linear.bias.grad)

dL/dw tensor([[-0.1362, -0.7179,  0.2245],
        [ 0.1557,  0.4533, -0.0275]])
dL/db tensor([-0.9013, -0.6864])


In [25]:
optimizer.step() # 위에서 수정된 값으로 하강을 진행한다...학습을 한다

# 반복효과
pred = linear(x)
loss = loss_function(pred, y)

print('loss afer BackPropagation : ', loss.item())

loss afer BackPropagation :  1.197208046913147
